name: geohasher
description: geohasher is a library for computing geohashes; geohashes are a public domain geocoding system
version: 0.6.0
author: Levi Cook <levicook@gmail.com>
homepage: https://github.com/levicook/geohasher

dev_dependencies:
  args: ^2.0.0
  test: ^1.6.4

environment:
  sdk: ">=2.12.0 <3.0.0"
